### ISSUE TITLE
Add a tool to insert notes next to the map elements

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#282] opened 2017-06-01 20:56 UTC
It would be useful to add a tool to insert notes next to the elements of the map (as a post-it) to remember their names or their contents for example. And make sure that these notes are only displayed in the editor.

**Comment by christopho** [comment] 2017-06-01 21:21
Duplicate of #281

**Closed as completed by christopho** 2017-06-01 21:21 UTC
