### ISSUE TITLE
Automatically add .lua file ending to scripts

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus-quest-editor#164] opened 2016-05-04 16:25 UTC
If you add a script called "foo" , you'll get "Wrong script name: 'foo' (should end with '.lua')". OK, if it should end with .lua, why aren't you just renaming it foo.lua for me?

**Comment by christopho** [comment] 2016-05-04 21:01
Duplicate of #46

**Closed by christopho** 2016-05-04 21:01 UTC
