### ISSUE TITLE
Feature Request: Allow a group of blue 8x8 blocks to be moved

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus-quest-editor#184] opened 2016-06-03 19:04 UTC
I know one is able to move one blue block, but it would be very helpful for when a graphic is moved on image file. I did however edit the image I moved, but it would still be very useful.

Check image.
![move a group of blue box 8x8 selections](https://cloud.githubusercontent.com/assets/19560764/15789868/3eac4108-2983-11e6-9a04-1572411ade4d.png)

**Comment by christopho** [comment] 2016-06-03 19:46
Duplicate of #171

**Closed by christopho** 2016-06-03 19:46 UTC
